version: '3'
services:
  api:
    image: wpm-api-prod
    container_name: wpm-api-prod
    expose:
      - '${APP_SERVER_PORT}'
    ports:
      - '${APP_SERVER_PORT}:${APP_SERVER_PORT}'
    environment:
      APP_SERVER_PORT: '${APP_SERVER_PORT}'
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
  web:
    image: wpm-host-prod
    container_name: wpm-host-prod
    ports:
      - '80:80'
    build: ./web
    depends_on:
      - api
